-- Run in Supabase → SQL Editor (entire script). Fixes 403 RLS on submit.

-- ─── Table: reports ─────────────────────────────────────────
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  urgency text not null,
  score double precision,
  anomaly double precision,
  detected jsonb default '[]'::jsonb,
  num_det integer default 0,
  latitude double precision,
  longitude double precision,
  location_str text,
  source text,
  image_url text,
  annot_url text
);

alter table public.reports enable row level security;

-- Table privileges (RLS still enforces row access). Supabase usually grants these; repeat if you still see 403.
grant usage on schema public to anon, authenticated;
grant select, insert on public.reports to anon, authenticated;

drop policy if exists "reports_insert_anon" on public.reports;
drop policy if exists "reports_select_anon" on public.reports;

create policy "reports_insert_anon"
  on public.reports for insert
  to anon
  with check (true);

create policy "reports_select_anon"
  on public.reports for select
  to anon
  using (true);

-- Optional: let authenticated users (if you add auth later) insert/select
create policy "reports_insert_authenticated"
  on public.reports for insert
  to authenticated
  with check (true);

create policy "reports_select_authenticated"
  on public.reports for select
  to authenticated
  using (true);

-- ─── Storage bucket + policies (uploads use anon key) ───────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'inspectRAIL-images',
  'inspectRAIL-images',
  true,
  15728640,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "storage_inspect_anon_insert" on storage.objects;
drop policy if exists "storage_inspect_anon_update" on storage.objects;
drop policy if exists "storage_inspect_public_read" on storage.objects;

create policy "storage_inspect_anon_insert"
  on storage.objects for insert
  to anon
  with check (bucket_id = 'inspectRAIL-images');

create policy "storage_inspect_anon_update"
  on storage.objects for update
  to anon
  using (bucket_id = 'inspectRAIL-images')
  with check (bucket_id = 'inspectRAIL-images');

create policy "storage_inspect_public_read"
  on storage.objects for select
  to public
  using (bucket_id = 'inspectRAIL-images');
