-- Run in Supabase SQL Editor (once per project)

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  urgency text not null,
  score double precision,
  anomaly double precision,
  detected jsonb default '[]'::jsonb,
  num_det integer default 0,
  latitude double precision,
  longitude double precision,
  location_str text,
  source text,
  image_url text,
  annot_url text
);

alter table public.reports enable row level security;

-- Public anon: demo / civic reporting (tighten for production)
create policy "reports_insert_anon"
  on public.reports for insert
  to anon
  with check (true);

create policy "reports_select_anon"
  on public.reports for select
  to anon
  using (true);

-- Storage: create bucket "inspectRAIL-images" in Dashboard → Storage (public)
